// champion.service.ts

import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ChampionService {
  private champions = [
{
      name:'Itadori Yuuji',
      gender:'Male',
      species:'Human',
      hair:'Pink',
      statusTip:'Alive',
      innateTechniques:'Blood Manipulation / Shrine',
      domainExpansion:'Unnamed',
      grade:'Unknow',
      mangaDebutTip:'1',
      arcDebut:'Prologue',
      photo: '../assets/images/itadori.png',
},
{
      name:'Satoru Gojo',
      gender:'Male',
      species:'Human',
      hair:'White',
      statusTip:'Deceased',
      innateTechniques:'Limitless / Six Eyes',
      domainExpansion:'Unlimited Void',
      grade:'Special',
      mangaDebutTip:'1',
      arcDebut:'Prologue',
      photo: '../assets/images/satoru.png',
},
{
      name:'Ryomen Sukuna',
      gender:'Male',
      species:'Human / Incarnation',
      hair:'Pink',
      statusTip:'Alive',
      innateTechniques:'Shrine / Divine Flame / Ten Shadowns Technique',
      domainExpansion:'Malevolent Shrine',
      grade:'Special',
      mangaDebutTip:'1',
      arcDebut:'Prologue',
      photo: '../assets/images/sukuna.png',
},
{
      name:'Megumi Fushiguro',
      gender:'Male',
      species:'Human',
      hair:'Black',
      statusTip:'Alive',
      innateTechniques:'Ten Shadowns Technique',
      domainExpansion:'Chimera Shadow Garden',
      grade:'2',
      mangaDebutTip:'1',
      arcDebut:'Prologue',
      photo: '../assets/images/megumi.png',
},
{
      name:'Yuta Okkotsu',
      gender:'Male',
      species:'Human',
      hair:'Black',
      statusTip:'Alive',
      innateTechniques:'Copy',
      domainExpansion:'Authentic Mutual Love',
      grade:'Special',
      mangaDebutTip:'137',
      arcDebut:'Itadori Extermination Arc',
      photo: '../assets/images/yuta.png',
},
{
      name:'Nobara Kugisaki',
      gender:'Female',
      species:'Human',
      hair:'Ginger',
      statusTip:'Unknow',
      innateTechniques:'Straw Doll Technique',
      domainExpansion:'None',
      grade:'3',
      mangaDebutTip:'3',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/nobara.png',
},
{
      name:'Masamichi Yaga',
      gender:'Male',
      species:'Human',
      hair:'Dark Brown',
      statusTip:'Deceased',
      innateTechniques:'Cursed Corpse',
      domainExpansion:'None',
      grade:'1',
      mangaDebutTip:'3',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/masamichi.png',
},
{
      name:'Atsuya Kusakabe',
      gender:'Male',
      species:'Human',
      hair:'Brown',
      statusTip:'Alive',
      innateTechniques:'None',
      domainExpansion:'None',
      grade:'1',
      mangaDebutTip:'83',
      arcDebut:'Itadori Extermination Arc',
      photo: '../assets/images/atsuya.png',
},
{
      name:'Kiyotaka Ijichi',
      gender:'Male',
      species:'Human',
      hair:'Black',
      statusTip:'Alive',
      innateTechniques:'None',
      domainExpansion:'None',
      grade:'Unknow',
      mangaDebutTip:'2',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/kiyotaka.png',
},
{
      name:'Shoko Ieiri',
      gender:'Female',
      species:'Human',
      hair:'Brown',
      statusTip:'Alive',
      innateTechniques:'None',
      domainExpansion:'None',
      grade:'Unknow',
      mangaDebutTip:'10',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/shoko.png',
},
{
      name:'Akari Nitta',
      gender:'Female',
      species:'Human',
      hair:'Blonde',
      statusTip:'Alive',
      innateTechniques:'None',
      domainExpansion:'None',
      grade:'Unknow',
      mangaDebutTip:'55',
      arcDebut:'Death Painting Arc',
      photo: '../assets/images/akari.png',
},
{
      name:'Maki Zenin',
      gender:'Female',
      species:'Human',
      hair:'Dark Green',
      statusTip:'Alive',
      innateTechniques:'Heavenly Restriction',
      domainExpansion:'None',
      grade:'4',
      mangaDebutTip:'10',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/maki.png',
},
{
      name:'Toge Inumaki',
      gender:'Male',
      species:'Human',
      hair:'Platinum Blonde',
      statusTip:'Alive',
      innateTechniques:'Cursed Speech',
      domainExpansion:'None',
      grade:'Semi 1',
      mangaDebutTip:'1',
      arcDebut:'Prologue',
      photo: '../assets/images/toge.png',
},
{
      name:'Panda',
      gender:'Male',
      species:'Cursed Corpse',
      hair:'No hair',
      statusTip:'Alive',
      innateTechniques:'None',
      domainExpansion:'None',
      grade:'Semi 2',
      mangaDebutTip:'1',
      arcDebut:'Prologue',
      photo: '../assets/images/panda.png',
},
{
      name:'Kinji Hakari',
      gender:'Male',
      species:'Human',
      hair:'Blonde',
      statusTip:'Alive',
      innateTechniques:'Private Pure Love Train',
      domainExpansion:'Idle Death Gamble',
      grade:'Unknow',
      mangaDebutTip:'153',
      arcDebut:'Perfect Preparation Arc',
      photo: '../assets/images/kinji.png',
},
{
      name:'Kirara Hoshi',
      gender:'Male',
      species:'Human',
      hair:'Black',
      statusTip:'Alive',
      innateTechniques:'Love Rendezvous',
      domainExpansion:'None',
      grade:'Unknow',
      mangaDebutTip:'153',
      arcDebut:'Perfect Preparation Arc',
      photo: '../assets/images/kirara.png',
},
{
      name:'Mahito',
      gender:'Male',
      species:'Cursed Spirit',
      hair:'Ligth Blue',
      statusTip:'Deceased',
      innateTechniques:'Idle Transfiguration',
      domainExpansion:'Self-Embodiment of Perfection',
      grade:'Special',
      mangaDebutTip:'16',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/mahito.png',
},
{
      name:'Jogo',
      gender:'Male',
      species:'Cursed Spirit',
      hair:'No hair',
      statusTip:'Deceased',
      innateTechniques:'Disaster Flames',
      domainExpansion:'Coffin of the Iron Mountain',
      grade:'Special',
      mangaDebutTip:'10',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/jogo.png',
},
{
      name:'Hanami',
      gender:'Male',
      species:'Cursed Spirit',
      hair:'No hair',
      statusTip:'Deceased',
      innateTechniques:'Disaster Plants',
      domainExpansion:'Shining Sea of Growing Branches',
      grade:'Special',
      mangaDebutTip:'10',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/hanami.png',
},
{
      name:'Dagon',
      gender:'Male',
      species:'Cursed Spirit',
      hair:'No hair',
      statusTip:'Deceased',
      innateTechniques:'Disaster Tides',
      domainExpansion:'Horizon of the Captivating Skandha',
      grade:'Special',
      mangaDebutTip:'10',
      arcDebut:'Fearsome Womb Arc',
      photo: '../assets/images/dagon.png',
},
{
      name:'Rika Orimoto',
      gender:'Female',
      species:'Cursed Spirit',
      hair:'No hair',
      statusTip:'Deceased',
      innateTechniques:'None',
      domainExpansion:'None',
      grade:'Special',
      mangaDebutTip:'137',
      arcDebut:'Itadori Extermination Arc',
      photo: '../assets/images/rika.png',
}
  ];

  constructor() { }

  getChampions() {
    return this.champions;
  }

  getChampion(name: string) {
    return this.champions.find(champion => champion.name.toLowerCase() === name.toLowerCase());
  }
}
